addpath('/users/bphan/bin/MATLAB/cellsegm/',...
    '/users/bphan/keri/cFos/',...
    ['/users/bphan/bin/MATLAB/MATLAB_Control_ZEN_from_MATLAB/'...
    'MATLAB_Control_ZEN_from_MATLAB'],...
    '/users/bphan/bin/MATLAB/bfmatlab',...
'/users/bphan/bin/MATLAB/bf-tools')
